---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: HEAD
    hooks:
      - id: trailing-whitespace
#  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
#    rev: HEAD
#    hooks:
#      - id: dockerfilelint
#        stages: [commit]

